#!/bin/bash
# ============================================
#  RenderDoc RT Preview Server Launcher
#  Auto-generated by Report Bundle Generator
# ============================================

echo ""
echo "===================================="
echo "  RenderDoc RT Preview Server"
echo "===================================="
echo ""

PORT=8765
RDC_FILE="$1"
SERVER_SCRIPT="d:\Code\git\renderdoc\scripts\rdc_analyzer\rt_preview_server.py"

# 检查参数
if [ -z "$RDC_FILE" ]; then
    echo "[INFO] 使用模式: Mock Mode (无需 RDC 文件)"
    echo "[INFO] 如需加载真实 RDC 文件，请运行:"
    echo "       ./start_rt_server.sh /path/to/capture.rdc"
    echo ""
fi

# 尝试查找 qrenderdoc
QRENDERDOC=""

# 方法1: 检查 PATH
if command -v qrenderdoc &> /dev/null; then
    QRENDERDOC=$(which qrenderdoc)
fi

# 方法2: 检查常见位置
if [ -z "$QRENDERDOC" ]; then
    COMMON_PATHS=(
        "/usr/local/bin/qrenderdoc"
        "/opt/renderdoc/bin/qrenderdoc"
        "$HOME/.local/bin/qrenderdoc"
    )
    for path in "${COMMON_PATHS[@]}"; do
        if [ -x "$path" ]; then
            QRENDERDOC="$path"
            break
        fi
    done
fi

if [ -n "$QRENDERDOC" ]; then
    echo "[INFO] 找到 qrenderdoc: $QRENDERDOC"
fi

if [ -n "$RDC_FILE" ]; then
    echo "[INFO] 优先使用 Python Headless 启动..."
    python3 "$SERVER_SCRIPT" --rdc "$RDC_FILE" --port $PORT
    if [ $? -ne 0 ] && [ -n "$QRENDERDOC" ]; then
        echo "[WARN] Python 启动失败，尝试 qrenderdoc..."
        "$QRENDERDOC" --script "$SERVER_SCRIPT" --rdc "$RDC_FILE" --port $PORT
    fi
else
    echo "[INFO] 使用 Python Mock Mode..."
    echo "[INFO] 这将返回测试数据，不会加载真实 RDC。"
    echo ""
    python3 "$SERVER_SCRIPT" --port $PORT --mock
    if [ $? -ne 0 ] && [ -n "$QRENDERDOC" ]; then
        echo "[WARN] Python 启动失败，尝试 qrenderdoc Mock..."
        "$QRENDERDOC" --script "$SERVER_SCRIPT" --port $PORT --mock
    fi
fi

echo ""
echo "[INFO] 服务器已停止"
