@echo off
REM ============================================
REM  RenderDoc RT Preview Server Launcher
REM  Auto-generated by Report Bundle Generator
REM ============================================

echo.
echo ====================================
echo   RenderDoc RT Preview Server
echo ====================================
echo.

REM 设置端口
set PORT=8765

REM 检查 RDC 文件参数
if "%~1"=="" (
    echo [INFO] 使用模式: Mock Mode ^(无需 RDC 文件^)
    echo [INFO] 如需加载真实 RDC 文件，请运行:
    echo        start_rt_server.bat "path\to\capture.rdc"
    echo.
    set RDC_FILE=
) else (
    set RDC_FILE=%~1
    echo [INFO] RDC 文件: %RDC_FILE%
)

REM 优先尝试 Python Headless（推荐）
set QRENDERDOC_PATH=

REM 方法1: 检查 PATH 中的 qrenderdoc
where qrenderdoc.exe >nul 2>&1
if %ERRORLEVEL%==0 (
    for /f "delims=" %%i in ('where qrenderdoc.exe') do set QRENDERDOC_PATH=%%i
    goto :found_qrenderdoc
)

REM 方法2: 检查常见安装位置
set COMMON_PATHS="C:\Program Files\RenderDoc\qrenderdoc.exe" ^
                 "C:\Program Files (x86)\RenderDoc\qrenderdoc.exe" ^
                 "%LOCALAPPDATA%\RenderDoc\qrenderdoc.exe"

for %%p in (%COMMON_PATHS%) do (
    if exist %%p (
        set QRENDERDOC_PATH=%%~p
        goto :found_qrenderdoc
    )
)

REM 如果未找到 qrenderdoc.exe，仍可使用 Python（Headless）
echo [WARN] 未找到 qrenderdoc.exe
echo [WARN] 将尝试使用 Python Headless 启动服务器...
echo.
goto :use_python

:found_qrenderdoc
echo [INFO] 找到 qrenderdoc: %QRENDERDOC_PATH%

REM 启动服务器（优先 Python Headless）
if defined RDC_FILE (
    echo [INFO] 优先使用 Python Headless 启动（无需 GUI）...
    py -3 "d:\Code\git\renderdoc\scripts\rdc_analyzer\rt_preview_server.py" --rdc "%RDC_FILE%" --port %PORT%
    if %ERRORLEVEL%==0 goto :end
    echo [WARN] Python 启动失败，尝试 qrenderdoc...
    "%QRENDERDOC_PATH%" --script "d:\Code\git\renderdoc\scripts\rdc_analyzer\rt_preview_server.py" --rdc "%RDC_FILE%" --port %PORT%
) else (
    echo [INFO] 使用 Python Mock Mode 启动服务器...
    py -3 "d:\Code\git\renderdoc\scripts\rdc_analyzer\rt_preview_server.py" --port %PORT% --mock
    if %ERRORLEVEL%==0 goto :end
    echo [WARN] Python 启动失败，尝试 qrenderdoc Mock...
    "%QRENDERDOC_PATH%" --script "d:\Code\git\renderdoc\scripts\rdc_analyzer\rt_preview_server.py" --port %PORT% --mock
)
goto :end

:use_python
REM 使用 Python 直接启动（优先 Headless）
if defined RDC_FILE (
    echo [INFO] 使用 Python Headless 启动服务器...
    py -3 "d:\Code\git\renderdoc\scripts\rdc_analyzer\rt_preview_server.py" --rdc "%RDC_FILE%" --port %PORT%
) else (
    echo [INFO] 使用 Python Mock Mode 启动服务器...
    echo [INFO] 这将返回测试数据，不会加载真实 RDC。
    echo.
    py -3 "d:\Code\git\renderdoc\scripts\rdc_analyzer\rt_preview_server.py" --port %PORT% --mock
)
goto :end

:end
echo.
echo [INFO] 服务器已停止
pause
