#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Standalone Mali Offline Compiler Analysis Script

This script analyzes extracted shaders from RenderDoc using Mali Offline Compiler.
It reads the manifest.json generated by extract_shaders.py and produces a HTML report.

Usage:
    py -3 analyze_extracted_shaders.py [--gpu Mali-G78]
"""

import os
import sys
import json
import argparse
import subprocess
import tempfile
from dataclasses import dataclass, field
from typing import Dict, Optional, List, Any


@dataclass
class MaliAnalysisResult:
    """Analysis result from Mali Offline Compiler"""
    success: bool = False
    error_message: str = ""
    cycles: Dict[str, float] = field(default_factory=dict)
    bottleneck: str = ""
    work_registers: int = 0
    uniform_registers: int = 0
    has_fp16: bool = False
    raw_json: Dict[str, Any] = field(default_factory=dict)


class MaliCompiler:
    """Wrapper for Mali Offline Compiler (malioc)"""
    
    def __init__(self, malioc_path: str, default_gpu: str = "Mali-G78"):
        self.malioc_path = malioc_path
        self.default_gpu = default_gpu
        self._version = None
    
    def is_available(self) -> bool:
        """Check if malioc is available"""
        return os.path.exists(self.malioc_path)
    
    def get_version(self) -> str:
        """Get malioc version"""
        if self._version:
            return self._version
        try:
            result = subprocess.run(
                [self.malioc_path, "--version"],
                capture_output=True, text=True, timeout=10
            )
            self._version = result.stdout.strip().split('\n')[0]
            return self._version
        except Exception:
            return "Unknown"
    
    def analyze_file(self, shader_path: str, shader_type: str = "fragment",
                     gpu: str = None) -> MaliAnalysisResult:
        """Analyze a shader file"""
        gpu = gpu or self.default_gpu
        
        # Map shader type to malioc option (use full --option names)
        stage_map = {
            'vertex': '--vertex',
            'fragment': '--fragment',
            'compute': '--compute',
            'vert': '--vertex',
            'frag': '--fragment',
        }
        stage_opt = stage_map.get(shader_type.lower(), '--fragment')
        
        try:
            result = subprocess.run(
                [
                    self.malioc_path,
                    "--format", "json",
                    "--core", gpu,
                    stage_opt,
                    shader_path
                ],
                capture_output=True, text=True, timeout=60
            )
            
            if result.returncode != 0:
                return MaliAnalysisResult(
                    success=False,
                    error_message=result.stderr or result.stdout
                )
            
            # Parse JSON output
            data = json.loads(result.stdout)
            return self._parse_json_output(data)
            
        except json.JSONDecodeError as e:
            return MaliAnalysisResult(success=False, error_message=f"JSON parse error: {e}")
        except subprocess.TimeoutExpired:
            return MaliAnalysisResult(success=False, error_message="Timeout")
        except Exception as e:
            return MaliAnalysisResult(success=False, error_message=str(e))
    
    def _parse_json_output(self, data: Dict[str, Any]) -> MaliAnalysisResult:
        """Parse malioc JSON output (Schema v2)"""
        result = MaliAnalysisResult(success=True, raw_json=data)
        
        try:
            # Get first shader result
            shaders = data.get("shaders", [])
            if not shaders:
                result.success = False
                result.error_message = "No shader data in output"
                return result
            
            shader = shaders[0]
            variants = shader.get("variants", [])
            if not variants:
                result.success = False
                result.error_message = "No variants in shader"
                return result
            
            variant = variants[0]
            
            # Parse properties (list format in v2)
            props = variant.get("properties", [])
            props_dict = {}
            for p in props:
                if isinstance(p, dict) and "name" in p and "value" in p:
                    props_dict[p["name"]] = p["value"]
            
            # Use the correct property names from malioc JSON schema v2
            result.work_registers = int(props_dict.get("work_registers_used", 0))
            result.uniform_registers = int(props_dict.get("uniform_registers_used", 0))
            # fp16_arithmetic is a numeric percentage (0-100), not a string
            fp16_val = props_dict.get("fp16_arithmetic", 0)
            result.has_fp16 = fp16_val > 0 if isinstance(fp16_val, (int, float)) else False
            
            # Parse performance cycles
            perf = variant.get("performance", {})
            pipelines = perf.get("pipelines", [])
            cycle_data = perf.get("shortest_path_cycles", {})
            cycle_counts = cycle_data.get("cycle_count", [])
            
            # Map pipeline names to cycle values by index
            bound_map = {
                "arith_total": "A", "arith_fma": "A", "arithmetic": "A",
                "load_store": "LS", "texture": "T", "varying": "V",
            }
            
            cycles = {}
            max_cycles = 0.0
            bottleneck = "A"
            
            for i, name in enumerate(pipelines):
                if i < len(cycle_counts):
                    val = cycle_counts[i]
                    unit = bound_map.get(name.lower(), name[0].upper())
                    cycles[unit] = val
                    if val > max_cycles:
                        max_cycles = val
                        bottleneck = unit
            
            result.cycles = cycles
            result.bottleneck = bottleneck
            
        except Exception as e:
            result.success = False
            result.error_message = f"Parse error: {e}"
        
        return result


def generate_html_report(results: list, output_path: str, gpu: str):
    """Generate HTML report from analysis results"""
    
    html_template = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mali Shader Analysis Report</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 20px; background: #f5f5f5; }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        h1 {{ color: #333; border-bottom: 2px solid #007acc; padding-bottom: 10px; }}
        .summary {{ background: #fff; padding: 15px; border-radius: 8px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .shader-card {{ background: #fff; padding: 15px; border-radius: 8px; margin-bottom: 15px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .shader-header {{ display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px; }}
        .shader-name {{ font-weight: bold; font-size: 1.1em; color: #333; }}
        .shader-type {{ padding: 3px 8px; border-radius: 4px; font-size: 0.85em; }}
        .type-vertex {{ background: #e3f2fd; color: #1565c0; }}
        .type-fragment {{ background: #fce4ec; color: #c2185b; }}
        .cycles-bar {{ display: flex; height: 24px; border-radius: 4px; overflow: hidden; margin: 10px 0; }}
        .cycle-segment {{ display: flex; align-items: center; justify-content: center; color: #fff; font-size: 0.75em; font-weight: bold; }}
        .seg-arith {{ background: #4caf50; }}
        .seg-ls {{ background: #2196f3; }}
        .seg-tex {{ background: #ff9800; }}
        .seg-vary {{ background: #9c27b0; }}
        .metrics {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; margin-top: 10px; }}
        .metric {{ background: #f8f9fa; padding: 8px; border-radius: 4px; text-align: center; }}
        .metric-value {{ font-size: 1.2em; font-weight: bold; color: #007acc; }}
        .metric-label {{ font-size: 0.8em; color: #666; }}
        .bottleneck {{ padding: 5px 10px; border-radius: 4px; display: inline-block; margin-top: 5px; }}
        .bound-A {{ background: #e8f5e9; color: #2e7d32; }}
        .bound-LS {{ background: #e3f2fd; color: #1565c0; }}
        .bound-T {{ background: #fff3e0; color: #ef6c00; }}
        .bound-V {{ background: #f3e5f5; color: #7b1fa2; }}
        .error {{ background: #ffebee; color: #c62828; padding: 10px; border-radius: 4px; }}
        .legend {{ display: flex; gap: 15px; flex-wrap: wrap; margin: 10px 0; }}
        .legend-item {{ display: flex; align-items: center; gap: 5px; }}
        .legend-color {{ width: 16px; height: 16px; border-radius: 3px; }}
    </style>
</head>
<body>
<div class="container">
    <h1>Mali Shader Analysis Report</h1>
    
    <div class="summary">
        <h3>Summary</h3>
        <p><strong>GPU Target:</strong> {gpu}</p>
        <p><strong>Total Shaders Analyzed:</strong> {total_analyzed}</p>
        <p><strong>Successful:</strong> {success_count}</p>
        <p><strong>Failed:</strong> {fail_count}</p>
        
        <div class="legend">
            <div class="legend-item"><div class="legend-color seg-arith"></div> Arithmetic</div>
            <div class="legend-item"><div class="legend-color seg-ls"></div> Load/Store</div>
            <div class="legend-item"><div class="legend-color seg-tex"></div> Texture</div>
            <div class="legend-item"><div class="legend-color seg-vary"></div> Varying</div>
        </div>
    </div>
    
    {shader_cards}
</div>
</body>
</html>
'''
    
    shader_cards = []
    success_count = 0
    fail_count = 0
    
    for r in results:
        if r.get('error'):
            fail_count += 1
            card = f'''
    <div class="shader-card">
        <div class="shader-header">
            <span class="shader-name">{r['file']}</span>
            <span class="shader-type type-{r.get('shader_type', 'unknown').lower()}">{r.get('shader_type', 'Unknown')}</span>
        </div>
        <div class="error">Error: {r['error']}</div>
    </div>
'''
        else:
            success_count += 1
            cycles = r.get('cycles', {})
            total = sum(cycles.values()) if cycles else 1
            
            # Build cycle bar
            bar_segments = []
            colors = {'A': 'arith', 'LS': 'ls', 'T': 'tex', 'V': 'vary'}
            names = {'A': 'Arith', 'LS': 'L/S', 'T': 'Tex', 'V': 'Vary'}
            
            for unit, val in cycles.items():
                if val > 0:
                    pct = (val / total * 100)
                    bar_segments.append(
                        f'<div class="cycle-segment seg-{colors.get(unit, "arith")}" style="width:{pct:.1f}%">'
                        f'{names.get(unit, unit)}: {val:.1f}</div>'
                    )
            
            cycle_bar = ''.join(bar_segments) if bar_segments else '<div class="cycle-segment seg-arith" style="width:100%">No data</div>'
            
            # Bottleneck
            bottleneck = r.get('bottleneck', 'A')
            bound_names = {'A': 'Arithmetic', 'LS': 'Load/Store', 'T': 'Texture', 'V': 'Varying'}
            
            # Metrics
            metrics_html = f'''
        <div class="metrics">
            <div class="metric">
                <div class="metric-value">{r.get('work_registers', 'N/A')}</div>
                <div class="metric-label">Work Registers</div>
            </div>
            <div class="metric">
                <div class="metric-value">{r.get('uniform_registers', 'N/A')}</div>
                <div class="metric-label">Uniform Registers</div>
            </div>
            <div class="metric">
                <div class="metric-value">{r.get('has_fp16', 'N/A')}</div>
                <div class="metric-label">FP16 Used</div>
            </div>
        </div>
'''
            
            card = f'''
    <div class="shader-card">
        <div class="shader-header">
            <span class="shader-name">{r['file']}</span>
            <span class="shader-type type-{r.get('shader_type', 'unknown').lower()}">{r.get('shader_type', 'Unknown')}</span>
        </div>
        <div class="cycles-bar">{cycle_bar}</div>
        <span class="bottleneck bound-{bottleneck}">Bound: {bound_names.get(bottleneck, bottleneck)}</span>
        {metrics_html}
    </div>
'''
        shader_cards.append(card)
    
    html = html_template.format(
        gpu=gpu,
        total_analyzed=len(results),
        success_count=success_count,
        fail_count=fail_count,
        shader_cards=''.join(shader_cards)
    )
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)
    
    return output_path


def parse_result(result: MaliAnalysisResult) -> dict:
    """Parse MaliAnalysisResult into report dict"""
    if not result.success:
        return {'error': result.error_message}
    
    return {
        'cycles': result.cycles,
        'bottleneck': result.bottleneck,
        'work_registers': result.work_registers,
        'uniform_registers': result.uniform_registers,
        'has_fp16': 'Yes' if result.has_fp16 else 'No',
    }


def main():
    parser = argparse.ArgumentParser(description='Analyze extracted shaders with Mali Offline Compiler')
    parser.add_argument('--input', '-i', 
                        default=r'd:\Code\git\renderdoc\scripts\rdc_analyzer\extracted_shaders',
                        help='Input directory with extracted shaders')
    parser.add_argument('--output', '-o',
                        default=r'd:\Code\git\renderdoc\scripts\rdc_analyzer\mali_report.html',
                        help='Output HTML report path')
    parser.add_argument('--gpu', '-g', default='Mali-G78',
                        help='Target GPU (default: Mali-G78)')
    parser.add_argument('--malioc', '-m',
                        default=r'D:\Program Files\Arm\Arm Performance Studio 2025.3\mali_offline_compiler\malioc.exe',
                        help='Path to malioc.exe')
    
    args = parser.parse_args()
    
    # Check input
    manifest_path = os.path.join(args.input, 'manifest.json')
    if not os.path.exists(manifest_path):
        print(f"[ERROR] Manifest not found: {manifest_path}")
        print("[INFO] Please run extract_shaders.py in RenderDoc first.")
        return 1
    
    # Check malioc
    if not os.path.exists(args.malioc):
        print(f"[ERROR] Mali Offline Compiler not found: {args.malioc}")
        return 1
    
    # Initialize compiler
    compiler = MaliCompiler(malioc_path=args.malioc, default_gpu=args.gpu)
    
    if not compiler.is_available():
        print("[ERROR] Mali Offline Compiler not available")
        return 1
    
    print(f"[INFO] Mali Offline Compiler: {compiler.get_version()}")
    print(f"[INFO] Target GPU: {args.gpu}")
    
    # Load manifest
    with open(manifest_path, 'r', encoding='utf-8') as f:
        manifest = json.load(f)
    
    print(f"[INFO] Found {manifest['extracted']} shader sets in manifest")
    
    # Analyze each shader
    results = []
    
    for shader_info in manifest.get('shaders', []):
        event_id = shader_info['eventId']
        
        # Analyze vertex shader
        if 'vertex_shader' in shader_info:
            vs_path = os.path.join(args.input, shader_info['vertex_shader'])
            if os.path.exists(vs_path):
                print(f"[ANALYZE] {shader_info['vertex_shader']}...")
                result = compiler.analyze_file(vs_path, shader_type='vertex')
                results.append({
                    'file': shader_info['vertex_shader'],
                    'event_id': event_id,
                    'shader_type': 'Vertex',
                    **parse_result(result)
                })
        
        # Analyze fragment shader
        if 'fragment_shader' in shader_info:
            ps_path = os.path.join(args.input, shader_info['fragment_shader'])
            if os.path.exists(ps_path):
                print(f"[ANALYZE] {shader_info['fragment_shader']}...")
                result = compiler.analyze_file(ps_path, shader_type='fragment')
                results.append({
                    'file': shader_info['fragment_shader'],
                    'event_id': event_id,
                    'shader_type': 'Fragment',
                    **parse_result(result)
                })
    
    # Generate report
    if results:
        report_path = generate_html_report(results, args.output, args.gpu)
        print(f"\n[DONE] Report generated: {report_path}")
        print(f"[INFO] Analyzed {len(results)} shaders")
    else:
        print("[WARN] No shaders analyzed")
    
    return 0


if __name__ == '__main__':
    sys.exit(main())