#!/usr/bin/env python3
"""
Server Scripts Generator - RT 预览服务启动脚本生成模块

从 report_bundle_generator.py 提取，负责：
- 生成 Windows batch 启动脚本
- 生成 Linux/Mac shell 启动脚本
- 生成 README 使用说明

Author: RDC Analyzer Team
Date: 2025-01-24
"""

from pathlib import Path
from typing import Dict


def generate_rt_server_scripts(
    output_dir: Path,
    rt_server_port: int = 8765
) -> Dict[str, str]:
    """
    生成 RT 预览服务的启动脚本
    
    Args:
        output_dir: 输出目录
        rt_server_port: RT 服务端口（默认 8765）
        
    Returns:
        {script_name: script_path} 字典
    """
    scripts = {}
    
    # 获取 rt_preview_server.py 的相对路径
    server_script = Path(__file__).parent / "rt_preview_server.py"
    
    # Windows Batch 脚本
    bat_content = _generate_windows_batch(server_script, rt_server_port)
    bat_path = output_dir / "start_rt_server.bat"
    bat_path.write_text(bat_content, encoding="gbk")  # Windows bat 使用 GBK
    scripts["start_script_bat"] = str(bat_path)
    
    # Linux/Mac Shell 脚本
    sh_content = _generate_unix_shell(server_script, rt_server_port)
    sh_path = output_dir / "start_rt_server.sh"
    sh_path.write_text(sh_content, encoding="utf-8")
    
    # 设置执行权限（仅 Unix）
    try:
        import stat
        sh_path.chmod(sh_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except Exception:
        pass  # Windows 上会失败，忽略
    
    scripts["start_script_sh"] = str(sh_path)
    
    # 生成 README 使用说明
    readme_content = _generate_readme(rt_server_port)
    readme_path = output_dir / "RT_SERVER_README.md"
    readme_path.write_text(readme_content, encoding="utf-8")
    scripts["rt_readme"] = str(readme_path)
    
    return scripts


def _generate_windows_batch(server_script: Path, port: int) -> str:
    """生成 Windows Batch 启动脚本"""
    return f'''@echo off
REM ============================================
REM  RenderDoc RT Preview Server Launcher
REM  Auto-generated by Report Bundle Generator
REM ============================================

echo.
echo ====================================
echo   RenderDoc RT Preview Server
echo ====================================
echo.

REM 设置端口
set PORT={port}

REM 检查 RDC 文件参数
if "%~1"=="" (
    echo [INFO] 使用模式: Mock Mode ^(无需 RDC 文件^)
    echo [INFO] 如需加载真实 RDC 文件，请运行:
    echo        start_rt_server.bat "path\\to\\capture.rdc"
    echo.
    set RDC_FILE=
) else (
    set RDC_FILE=%~1
    echo [INFO] RDC 文件: %RDC_FILE%
)

REM 优先尝试 Python Headless（推荐）
set QRENDERDOC_PATH=

REM 方法1: 检查 PATH 中的 qrenderdoc
where qrenderdoc.exe >nul 2>&1
if %ERRORLEVEL%==0 (
    for /f "delims=" %%i in ('where qrenderdoc.exe') do set QRENDERDOC_PATH=%%i
    goto :found_qrenderdoc
)

REM 方法2: 检查常见安装位置
set COMMON_PATHS="C:\\Program Files\\RenderDoc\\qrenderdoc.exe" ^
                 "C:\\Program Files (x86)\\RenderDoc\\qrenderdoc.exe" ^
                 "%LOCALAPPDATA%\\RenderDoc\\qrenderdoc.exe"

for %%p in (%COMMON_PATHS%) do (
    if exist %%p (
        set QRENDERDOC_PATH=%%~p
        goto :found_qrenderdoc
    )
)

REM 如果未找到 qrenderdoc.exe，仍可使用 Python（Headless）
echo [WARN] 未找到 qrenderdoc.exe
echo [WARN] 将尝试使用 Python Headless 启动服务器...
echo.
goto :use_python

:found_qrenderdoc
echo [INFO] 找到 qrenderdoc: %QRENDERDOC_PATH%

REM 启动服务器（优先 Python Headless）
if defined RDC_FILE (
    echo [INFO] 优先使用 Python Headless 启动（无需 GUI）...
    py -3 "{server_script}" --rdc "%RDC_FILE%" --port %PORT%
    if %ERRORLEVEL%==0 goto :end
    echo [WARN] Python 启动失败，尝试 qrenderdoc...
    "%QRENDERDOC_PATH%" --script "{server_script}" --rdc "%RDC_FILE%" --port %PORT%
) else (
    echo [INFO] 使用 Python Mock Mode 启动服务器...
    py -3 "{server_script}" --port %PORT% --mock
    if %ERRORLEVEL%==0 goto :end
    echo [WARN] Python 启动失败，尝试 qrenderdoc Mock...
    "%QRENDERDOC_PATH%" --script "{server_script}" --port %PORT% --mock
)
goto :end

:use_python
REM 使用 Python 直接启动（优先 Headless）
if defined RDC_FILE (
    echo [INFO] 使用 Python Headless 启动服务器...
    py -3 "{server_script}" --rdc "%RDC_FILE%" --port %PORT%
) else (
    echo [INFO] 使用 Python Mock Mode 启动服务器...
    echo [INFO] 这将返回测试数据，不会加载真实 RDC。
    echo.
    py -3 "{server_script}" --port %PORT% --mock
)
goto :end

:end
echo.
echo [INFO] 服务器已停止
pause
'''


def _generate_unix_shell(server_script: Path, port: int) -> str:
    """生成 Linux/Mac Shell 启动脚本"""
    return f'''#!/bin/bash
# ============================================
#  RenderDoc RT Preview Server Launcher
#  Auto-generated by Report Bundle Generator
# ============================================

echo ""
echo "===================================="
echo "  RenderDoc RT Preview Server"
echo "===================================="
echo ""

PORT={port}
RDC_FILE="$1"
SERVER_SCRIPT="{server_script}"

# 检查参数
if [ -z "$RDC_FILE" ]; then
    echo "[INFO] 使用模式: Mock Mode (无需 RDC 文件)"
    echo "[INFO] 如需加载真实 RDC 文件，请运行:"
    echo "       ./start_rt_server.sh /path/to/capture.rdc"
    echo ""
fi

# 尝试查找 qrenderdoc
QRENDERDOC=""

# 方法1: 检查 PATH
if command -v qrenderdoc &> /dev/null; then
    QRENDERDOC=$(which qrenderdoc)
fi

# 方法2: 检查常见位置
if [ -z "$QRENDERDOC" ]; then
    COMMON_PATHS=(
        "/usr/local/bin/qrenderdoc"
        "/opt/renderdoc/bin/qrenderdoc"
        "$HOME/.local/bin/qrenderdoc"
    )
    for path in "${{COMMON_PATHS[@]}}"; do
        if [ -x "$path" ]; then
            QRENDERDOC="$path"
            break
        fi
    done
fi

if [ -n "$QRENDERDOC" ]; then
    echo "[INFO] 找到 qrenderdoc: $QRENDERDOC"
fi

if [ -n "$RDC_FILE" ]; then
    echo "[INFO] 优先使用 Python Headless 启动..."
    python3 "$SERVER_SCRIPT" --rdc "$RDC_FILE" --port $PORT
    if [ $? -ne 0 ] && [ -n "$QRENDERDOC" ]; then
        echo "[WARN] Python 启动失败，尝试 qrenderdoc..."
        "$QRENDERDOC" --script "$SERVER_SCRIPT" --rdc "$RDC_FILE" --port $PORT
    fi
else
    echo "[INFO] 使用 Python Mock Mode..."
    echo "[INFO] 这将返回测试数据，不会加载真实 RDC。"
    echo ""
    python3 "$SERVER_SCRIPT" --port $PORT --mock
    if [ $? -ne 0 ] && [ -n "$QRENDERDOC" ]; then
        echo "[WARN] Python 启动失败，尝试 qrenderdoc Mock..."
        "$QRENDERDOC" --script "$SERVER_SCRIPT" --port $PORT --mock
    fi
fi

echo ""
echo "[INFO] 服务器已停止"
'''


def _generate_readme(port: int) -> str:
    """生成 README 使用说明"""
    return f'''# RT 预览服务使用说明

## 功能说明

RT 预览服务允许您在浏览器查看报告时，按需从 RDC 文件加载 Render Target **与纹理缩略图**。
这避免了预先导出大量图片，节省时间和磁盘空间。

## 使用方法

### Windows

1. **双击运行** `start_rt_server.bat`
2. 或使用 Python Headless（推荐）：
   ```
   py -3 rt_preview_server.py --rdc "path\\to\\your_capture.rdc" --port {port}
   ```
3. 如需加载真实 RDC 文件：
   ```
   start_rt_server.bat "path\\to\\your_capture.rdc"
   ```

### Linux/Mac

1. 运行脚本：
   ```bash
   ./start_rt_server.sh /path/to/your_capture.rdc
   ```

## 服务信息

- **端口**: {port}
- **API 端点**: `http://localhost:{port}/api/rt/{{eid}}`
- **纹理端点**: `http://localhost:{port}/api/texture/{{id}}`

## 在报告中使用

1. 启动 RT 预览服务器
2. 打开 `events.html` 或 `textures.html`
3. 在事件页点击「从 RDC 加载」或在纹理页点击「显示缩略图」
4. 系统会自动请求对应 EID 的 Render Target 或纹理缩略图

## 故障排除

### 服务器无法启动

- 确保已安装 RenderDoc（需要 qrenderdoc.exe）
- 确保端口 {port} 未被占用

### 图片加载失败

- 检查浏览器控制台是否有 CORS 错误
- 确认服务器正在运行
- 某些事件可能没有可用的 Render Target

## 技术细节

服务器使用 RenderDoc 的 Python API 进行实时截图：
1. 设置帧事件 (`controller.SetFrameEvent`)
2. 导出当前 RT (`controller.SaveTexture`)
3. 返回 Base64 编码的 PNG 图片
'''
